let latestWorkspaceEmail = 
workspace_owner
| where isnotempty( trim(" ", PrimaryEmail)) or isnotempty( trim(" ", SecondaryEmail))
| extend emails = strcat(PrimaryEmail,";",SecondaryEmail)
| summarize arg_max(ingestion_time(), emails) by workspaceId
| project emails, workspaceId;
AOPAlertLogs
| where ingestion_time() > ago(10min)
| extend IngestionTime = ingestion_time()
| summarize arg_max(CreationTime,*) by WorkspaceId, Id
| where AlertStatus == "Initial"
| join kind=leftanti (
    latestWorkspaceEmail
) on $left.WorkspaceId == $right.workspaceId
| project WorkspaceId, ToChangeAOP, AOP, AOPMustBe, CreationTime, UserId, AlertStatus = "NoEmail", Id, UserKey