let latestWorkspaceEmail = 
workspace_owner
| where isnotempty( trim(" ", PrimaryEmail)) or isnotempty( trim(" ", SecondaryEmail))
| extend emails = strcat(PrimaryEmail,";",SecondaryEmail)
| summarize arg_max(ingestion_time(), emails) by workspaceId
| project emails, workspaceId;
AOPAlertLogs
| where ingestion_time() > ago(10min)
| extend IngestionTime = ingestion_time()
| summarize arg_max(CreationTime, UserId, AlertStatus, Id, AOPMustBe, AOP, UserKey) by WorkspaceId, Id
| where AlertStatus == "Initial"
| join kind=inner (
    latestWorkspaceEmail
) on $left.WorkspaceId == $right.workspaceId
| project WorkspaceId,
    emails,
    Id,
    htmlRow = strcat(
    '<tr>',
    '<td style="padding:8px;">' , WorkspaceId, '</td>',
    '<td style="padding:8px;">', AOPMustBe, '</td>',
    '<td style="padding:8px;">', AOP, '</td>',
    '<td style="padding:8px;">', UserKey, '</td>',
    '<td style="padding:8px;">', format_datetime(CreationTime, 'yyyy-MM-dd HH:mm'), '</td>',
    '</tr>'
)
| summarize HtmlRows = strcat_array(make_list(htmlRow), ''),
    Ids = strcat_array(make_list(Id),", ") by WorkspaceId, emails