<#
.SYNOPSIS
    Recovers metrics for a previously executed benchmark run whose collection
    step failed (e.g. due to a transient 520 from .show queries).

.DESCRIPTION
    Re-runs the .show queries collection, ingests rows into BenchmarkResults,
    and writes detail + summary CSVs for the specified RunId. The benchmark
    iterations themselves must already exist in the engine's query history
    (Eventhouse retains .show queries for a limited window).

.PARAMETER RunId
    The full run identifier to recover, e.g. 'postload-20260429143734'.
    This is the value generated by Run-Benchmarks.ps1 and embedded in every
    ClientActivityId of the form 'bench:<RunId>:<QueryName>:<Iteration>'.

.PARAMETER RunLabel
    Optional friendly label to write into BenchmarkResults / CSVs. If omitted,
    extracted from RunId (everything before the last '-').

.EXAMPLE
    .\Testing\StressTest\Collect-BenchmarkRun.ps1 @common -RunId 'postload-20260429143734'
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string] $QueryUri,
    [Parameter(Mandatory = $true)] [string] $DatabaseName,
    [Parameter(Mandatory = $true)] [string] $KqlAuthToken,
    [Parameter(Mandatory = $true)] [string] $RunId,
    [string] $RunLabel,
    [string] $OutputFolder = (Join-Path $PSScriptRoot 'Results')
)

$ErrorActionPreference = 'Stop'

if (-not $RunLabel) {
    if ($RunId -match '^(.+)-\d{14}$') { $RunLabel = $Matches[1] } else { $RunLabel = $RunId }
}

$mgmtUri    = "$QueryUri/v1/rest/mgmt"
$queryUri2  = "$QueryUri/v1/rest/query"
$baseHeaders = @{
    Authorization  = "Bearer $KqlAuthToken"
    'Content-Type' = 'application/json'
}

function Invoke-Kql {
    param(
        [Parameter(Mandatory)] [string] $Csl,
        [ValidateSet('mgmt','query')] [string] $Endpoint = 'query',
        [int] $TimeoutSec = 600,
        [int] $MaxAttempts = 4
    )
    $uri = if ($Endpoint -eq 'mgmt') { $mgmtUri } else { $queryUri2 }
    $body = @{ csl = $Csl; db = $DatabaseName } | ConvertTo-Json -Depth 4
    for ($attempt = 1; $attempt -le $MaxAttempts; $attempt++) {
        try {
            return Invoke-RestMethod -Uri $uri -Method Post -Headers $baseHeaders -Body $body -TimeoutSec $TimeoutSec
        } catch [System.Net.WebException] {
            $resp = $_.Exception.Response
            $statusCode = if ($resp) { [int]$resp.StatusCode } else { 0 }
            $detail = ''
            if ($resp) {
                try { $sr = New-Object System.IO.StreamReader($resp.GetResponseStream()); $detail = $sr.ReadToEnd() } catch { }
            }
            if (($statusCode -in @(429,503,520)) -and $attempt -lt $MaxAttempts) {
                $backoff = [int]([math]::Pow(2, $attempt) * 5)
                Write-Warning "  KQL failed ($statusCode). Retry $attempt/$($MaxAttempts-1) in ${backoff}s..."
                Start-Sleep -Seconds $backoff
                continue
            }
            Write-Host "KQL request failed:" -ForegroundColor Red
            Write-Host $Csl -ForegroundColor DarkGray
            Write-Host $detail -ForegroundColor DarkGray
            throw
        }
    }
}

# ---------------------------------------------------------------------------
# Ensure target table exists (idempotent)
# ---------------------------------------------------------------------------
$createTable = @'
.create-merge table BenchmarkResults (
    RunId:string,
    RunLabel:string,
    QueryName:string,
    Iteration:int,
    ClientRequestId:string,
    StartedOn:datetime,
    DurationMs:long,
    CpuMs:long,
    MemoryPeakMB:real,
    TotalRows:long,
    ScannedRows:long,
    CacheHotHitMB:real,
    CacheColdHitMB:real,
    State:string,
    FailureReason:string,
    CapturedAt:datetime
)
'@
Write-Host "Ensuring BenchmarkResults table..." -ForegroundColor Cyan
Invoke-Kql -Csl $createTable -Endpoint mgmt | Out-Null

# ---------------------------------------------------------------------------
# Collect from .show queries
# ---------------------------------------------------------------------------
$prefix = 'bench:{0}:' -f $RunId
$collect = @"
.show queries
| where ClientActivityId startswith '$prefix'
| extend Parts     = split(ClientActivityId, ':')
| extend QueryName = tostring(Parts[2]),
         Iteration = toint(Parts[3])
| extend CacheJson    = parse_json(tostring(CacheStatistics))
| extend ScannedJson  = parse_json(tostring(ScannedExtentsStatistics))
| project ClientRequestId = ClientActivityId,
          QueryName,
          Iteration,
          StartedOn,
          DurationMs       = tolong(Duration / 1ms),
          CpuMs            = tolong(TotalCpu / 1ms),
          MemoryPeakMB     = todouble(MemoryPeak) / 1024.0 / 1024.0,
          TotalRows        = tolong(ScannedJson.TotalRowsCount),
          ScannedRows      = tolong(ScannedJson.ScannedRowsCount),
          CacheHotHitMB    = todouble(CacheJson.Shards.Hot.HitBytes)  / 1024.0 / 1024.0,
          CacheColdHitMB   = todouble(CacheJson.Shards.Cold.HitBytes) / 1024.0 / 1024.0,
          State,
          FailureReason
"@

Write-Host "Collecting metrics for run '$RunId'..." -ForegroundColor Cyan
$resp = Invoke-Kql -Csl $collect -Endpoint mgmt -TimeoutSec 600

$primary = $resp.Tables | Where-Object {
    $_.TableName -eq 'Table_0' -or $_.Name -eq 'PrimaryResult'
} | Select-Object -First 1
if (-not $primary) { $primary = @($resp.Tables)[0] }

if (-not $primary -or $primary.Rows.Count -eq 0) {
    Write-Warning "No rows found for prefix '$prefix'. Either the RunId is wrong or .show queries already aged out the entries."
    return
}

$colNames = $primary.Columns | ForEach-Object { $_.ColumnName }
function Get-Cell { param($row, [string]$name) $idx = $colNames.IndexOf($name); if ($idx -lt 0) { $null } else { $row[$idx] } }
function Esc      { param($s) if ($null -eq $s) { '' } else { ($s -replace '"','""') } }

$capturedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
$rowsCsv       = New-Object System.Collections.Generic.List[string]
$detailObjects = New-Object System.Collections.Generic.List[object]

foreach ($row in $primary.Rows) {
    $rec = [pscustomobject]@{
        RunId            = $RunId
        RunLabel         = $RunLabel
        QueryName        = (Get-Cell $row 'QueryName')
        Iteration        = (Get-Cell $row 'Iteration')
        ClientRequestId  = (Get-Cell $row 'ClientRequestId')
        StartedOn        = (Get-Cell $row 'StartedOn')
        DurationMs       = (Get-Cell $row 'DurationMs')
        CpuMs            = (Get-Cell $row 'CpuMs')
        MemoryPeakMB     = (Get-Cell $row 'MemoryPeakMB')
        TotalRows        = (Get-Cell $row 'TotalRows')
        ScannedRows      = (Get-Cell $row 'ScannedRows')
        CacheHotHitMB    = (Get-Cell $row 'CacheHotHitMB')
        CacheColdHitMB   = (Get-Cell $row 'CacheColdHitMB')
        State            = (Get-Cell $row 'State')
        FailureReason    = (Get-Cell $row 'FailureReason')
        CapturedAt       = $capturedAt
    }
    $detailObjects.Add($rec)
    $vals = @(
        $rec.RunId, $rec.RunLabel, $rec.QueryName, $rec.Iteration, $rec.ClientRequestId,
        $rec.StartedOn, $rec.DurationMs, $rec.CpuMs, $rec.MemoryPeakMB,
        $rec.TotalRows, $rec.ScannedRows,
        $rec.CacheHotHitMB, $rec.CacheColdHitMB, $rec.State, $rec.FailureReason, $rec.CapturedAt
    )
    $quoted = $vals | ForEach-Object { '"' + (Esc $_) + '"' }
    $rowsCsv.Add( ($quoted -join ',') )
}

# ---------------------------------------------------------------------------
# De-dup: skip ingest if this RunId already has rows in BenchmarkResults
# ---------------------------------------------------------------------------
$existsResp = Invoke-Kql -Csl "BenchmarkResults | where RunId == '$RunId' | count" -Endpoint query
$existsRow  = ($existsResp.Tables | Where-Object { $_.TableName -eq 'Table_0' -or $_.Name -eq 'PrimaryResult' } | Select-Object -First 1).Rows
$existsCount = if ($existsRow -and $existsRow.Count -gt 0) { [int64]$existsRow[0][0] } else { 0 }

if ($existsCount -gt 0) {
    Write-Warning "BenchmarkResults already has $existsCount rows for RunId '$RunId'. Skipping ingest (CSV will still be exported)."
} else {
    $ingestCmd = ".ingest inline into table BenchmarkResults with (format='csv') <|`n" + ($rowsCsv -join "`n")
    Invoke-Kql -Csl $ingestCmd -Endpoint mgmt -TimeoutSec 600 | Out-Null
    Write-Host "Persisted $($rowsCsv.Count) rows to BenchmarkResults." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# Detail CSV
# ---------------------------------------------------------------------------
if (-not (Test-Path $OutputFolder)) {
    New-Item -ItemType Directory -Path $OutputFolder -Force | Out-Null
}
$detailCsvPath = Join-Path $OutputFolder ("benchmark_detail_{0}.csv" -f $RunId)
$detailObjects | Export-Csv -Path $detailCsvPath -NoTypeInformation -Encoding UTF8
Write-Host "Detail CSV: $detailCsvPath" -ForegroundColor Green

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
$summary = @"
BenchmarkResults
| where RunId == '$RunId'
| summarize Runs=count(),
            P50=percentile(DurationMs,50),
            P95=percentile(DurationMs,95),
            Max=max(DurationMs),
            AvgCpuMs=avg(CpuMs),
            AvgMemMB=avg(MemoryPeakMB),
            AvgTotalRows=avg(TotalRows),
            AvgScannedRows=avg(ScannedRows)
  by QueryName
| order by P95 desc
"@
$resp2 = Invoke-Kql -Csl $summary -Endpoint query
$primary2 = $resp2.Tables | Where-Object { $_.TableName -eq 'Table_0' -or $_.Name -eq 'PrimaryResult' } | Select-Object -First 1
if ($primary2 -and $primary2.Rows.Count -gt 0) {
    Write-Host "`nSummary for run '$RunId':" -ForegroundColor Yellow
    $cols = $primary2.Columns | ForEach-Object { $_.ColumnName }
    $summaryObjects = foreach ($r in $primary2.Rows) {
        $obj = [ordered]@{ RunId = $RunId; RunLabel = $RunLabel }
        for ($k = 0; $k -lt $cols.Count; $k++) { $obj[$cols[$k]] = $r[$k] }
        [pscustomobject]$obj
    }
    $summaryObjects | Format-Table -AutoSize -Wrap | Out-String | Write-Host

    $summaryCsvPath = Join-Path $OutputFolder ("benchmark_summary_{0}.csv" -f $RunId)
    $summaryObjects | Export-Csv -Path $summaryCsvPath -NoTypeInformation -Encoding UTF8
    Write-Host "Summary CSV: $summaryCsvPath" -ForegroundColor Green
}

Write-Host "`nDone." -ForegroundColor Green
